### PR TITLE
Add FreeBSD platform

### PR DESCRIPTION
**Pull request by nunotexbsd**

### CODE REVIEW

**Review by nunotexbsd — COMMENTED** [review]
Add FreeBSD platform

**Review by marzojr — APPROVED** [review]

**Comment by nunotexbsd** [comment]
Thanks @marzojr

**Comment by nunotexbsd** [comment]
Sorry about my inexperience but I think I missed a tab in version.cc:
```
#elif (defined(FREEBSD))
out << "FreeBSD";
#elif (defined(MACOSX))
	out << "Mac OS X";
```

**Comment by DominusExult** [comment]
I wonder if we should replace this with fewer ifdefs with SDl_GetPlatform https://wiki.libsdl.org/SDL_GetPlatform
It's pretty generic but apart from Windows version detection we were just as basic anyway.

**Comment by wench** [comment]
Yep SDL_GetPlatform seems to exist exactly for this reason. Shame it doesn't give more detailed version information like we do for Windows. Seems like we should use it

**Pull request merged**
