### PR TITLE
Fixes for Teleport Here and both Stockings artwork

### PR DESCRIPTION
**Pull request by KnightCaptain**
This fixes Sprite 07, which is the blue one, typically used when an NPC teleports to a location.

This changes frames 5, 8-10, 13, 14 to make the circles more symmetrical and to add missing columns of pixels. The change is most clear on 14 which was missing 3 columns of pixels on the left.

### CODE REVIEW

**Comment by marzojr** [comment]
Can you add some before and after screenshots so I can see the difference?

**Comment by KnightCaptain** [comment]
Okay, I've added the before-and-after PNG files for each SHP submitted. This will allow you to see all of the changes. I've also updated the readme as well.

**Comment by marzojr** [comment]
Ack, I am sorry, I should have been clearer: I was asking you to put the pngs into something like imgur.com so I could see the differences more easily, definitely *not* on the pull request.

**Comment by marzojr** [comment]
The idea was that I could see what the pull request does without having to be at my computer, which is mostly turned off at home these days.

**Comment by DominusExult** [comment]
KC, can you remove the png from the pull request again? And show the changes in a screenshot outside of the request? I cannot see a difference in the teleport here screenshot.

**Comment by marzojr** [comment]
No need for removing, I can pull it manually and remove the commits.

**Comment by KnightCaptain** [comment]
My apologies, I may have misinterpreted a prior suggestion from @DominusExult that side-by-side comparison images would be useful. Since I have many more small art fixes, would it be better to close this pull and create a new one along with a matching Imgur post?

**Comment by KnightCaptain** [comment]
The web console isn't helping me get this done.

**Comment by DominusExult** [comment]
Yeah, sorry, I had mentioned this for your art repository https://github.com/KnightCaptain/exult_art
I still think for that a easy webviewable picture would be nice along with the shape files.

**Comment by marzojr** [comment]
Just add the PNGs to imgur and link to them here on a comment, I can work on extracting the correct commits.

**Comment by DominusExult** [comment]
I've finally added the two fixes directly by cherry picking from your fork. Sorry it took so long.

**Pull request closed without merging**
