### PR TITLE
Update exultmsg_de.txt

### PR DESCRIPTION
**Pull request by ungesundes-halbwissen**
changed some expressions, 
changed Wächter to Guardian, 
changed formal addressing to informal addressing
added all text required for Serpent Isle

### CODE REVIEW

**Comment by DominusExult** [comment]
I'm not sure I can accept that.
(Except for the message LB on Twitter but we need the @ in Exult first which @marzojr wanted to add some time ago).
The exultmsg_de.txt is for the official German release and AFAIR I used the correct lines for that.
 However we should probably add the functionality that Exult looks in the static folder for the exultmsg.txt as well for complete translations like yours.

**Comment by ungesundes-halbwissen** [comment]
Yeah, the old file was the official translation of 1992. What do you mean: the "Guardian" modification? The new spelling rules? Or the informal stuff? The rest should be unique (either Exult-only or Serpent Isle stuff)

But as I said before: Do as you deem appropriate and reject anything I do at will yourself - no hard feelings at any account :-)
It would be nice to have the file ready for Serpent Isle though

**Comment by DominusExult** [comment]
Not sure whether my full response shows after the initial sentence.
The exultmsg text files should be only reflecting the official releases and nit the fan translations (regardless of how much I appreciate it).
With the only exception of pointing at Twitter for reporting thy feat! (And for that we still need to implement the winning screen)
So for your translation you have to work with a patch folder  and your exultmsg being in that.
And in your SI Fixes mod translation you need to place the file again as Exult will ignore the patch folder when you start a mod.

**Comment by ungesundes-halbwissen** [comment]
Ok 👍 :-)

**Pull request closed without merging**
